import type { Config } from 'tailwindcss';
import { fontFamily } from 'tailwindcss/defaultTheme';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      maxWidth: {
        '8xl': '90rem', // 1440px
        '9xl': '100rem', // 1600px
      },
      keyframes: {
        shake: {
          '0%': { transform: 'translateX(0)' },
          '10%': { transform: 'translateX(-2px) rotate(-1deg)' },
          '20%': { transform: 'translateX(3px) rotate(1deg)' },
          '30%': { transform: 'translateX(-3px) rotate(-1.5deg)' },
          '40%': { transform: 'translateX(2px) rotate(1deg)' },
          '50%': { transform: 'translateX(-1px) rotate(-0.5deg)' },
          '60%': { transform: 'translateX(2px) rotate(1deg)' },
          '70%': { transform: 'translateX(-2px) rotate(-1deg)' },
          '80%': { transform: 'translateX(1px) rotate(0.5deg)' },
          '90%': { transform: 'translateX(-1px) rotate(-0.5deg)' },
          '100%': { transform: 'translateX(0)' },
        },
      },
      animation: {
        shake: 'shake 0.5s ease-in-out',
      },
      colors: {
        // Semantic tokens: these adapt when the theme changes.
        canvas: 'var(--canvas)',
        surface: 'var(--surface)',
        'surface-card': 'var(--surface-card)',
        'surface-muted': 'var(--surface-muted)',
        'surface-subtle': 'var(--surface-subtle)',
        'surface-inverse': 'var(--surface-inverse)',
        ink: 'var(--ink)',
        content: 'var(--content)',
        'content-muted': 'var(--content-muted)',
        'content-soft': 'var(--content-soft)',
        'content-inverse': 'var(--content-inverse)',
        border: 'var(--border)',
        'border-subtle': 'var(--border-subtle)',
        'surface-glass': 'var(--surface-glass)',
        'surface-glass-strong': 'var(--surface-glass-strong)',
        'inverse-glass': 'var(--inverse-glass)',
        'inverse-glass-strong': 'var(--inverse-glass-strong)',
        shadow: 'var(--shadow)',
        'shadow-soft': 'var(--shadow-soft)',
        'shadow-strong': 'var(--shadow-strong)',
        'glow-flame': 'var(--glow-flame)',
        'code-surface': 'var(--code-surface)',
        'code-content': 'var(--code-content)',
        'code-muted': 'var(--code-muted)',
        'code-accent': 'var(--code-accent)',
        'code-highlight': 'var(--code-highlight)',
        'code-border': 'var(--code-border)',

        // Literal palette tokens: use only for intentional branded accents.
        lemon: 'var(--lemon)',
        'flame-300': 'var(--flame-300)',
        'flame-500': 'var(--flame-500)',
        'flame-700': 'var(--flame-700)',
        'flame-900': 'var(--flame-900)',
        'gray-100': 'var(--gray-100)',
        'gray-300': 'var(--gray-300)',
        'gray-500': 'var(--gray-500)',
        'gray-700': 'var(--gray-700)',
        'gray-900': 'var(--gray-900)',
        'cocoa-700': 'var(--cocoa-700)',
        'cocoa-900': 'var(--cocoa-900)',
      },
      fontFamily: {
        heading: ['var(--font-heading)', ...fontFamily.sans],
        body: ['var(--font-body)', ...fontFamily.sans],
        bodyBold: ['var(--font-bodyBold)', ...fontFamily.sans],
        flashy: ['var(--font-flashy)', ...fontFamily.sans],
        drool: ['var(--font-drool)', ...fontFamily.sans],
        awkward: ['var(--font-awkward)', ...fontFamily.sans],
        spacey: ['var(--font-spacey)', ...fontFamily.sans],
        playful: ['var(--font-playful)', ...fontFamily.sans],
        saucy: ['var(--font-saucy)', ...fontFamily.sans],
        loud: ['var(--font-loud)', ...fontFamily.sans],
      },
      fontSize: {
        xs: ['var(--font-xs)', { lineHeight: '1rem' }],
        sm: ['var(--font-sm)', { lineHeight: '1.25rem' }],
        base: ['var(--font-base)', { lineHeight: '1.5rem' }],
        lg: ['var(--font-lg)', { lineHeight: '1.75rem' }],
        xl: ['var(--font-xl)', { lineHeight: '1.75rem' }],
        '2xl': ['var(--font-2xl)', { lineHeight: '2rem' }],
        '3xl': ['var(--font-3xl)', { lineHeight: '2.25rem' }],
        '4xl': ['var(--font-4xl)', { lineHeight: '2.5rem' }],
        '5xl': ['var(--font-5xl)', { lineHeight: '1' }],
        '6xl': ['var(--font-6xl)', { lineHeight: '1' }],
        '7xl': ['var(--font-7xl)', { lineHeight: '1' }],
        '8xl': ['var(--font-8xl)', { lineHeight: '1' }],
        '9xl': ['var(--font-9xl)', { lineHeight: '1' }],
      },
      spacing: {
        1: 'var(--space-1, 0.25rem)',
        2: 'var(--space-2, 0.5rem)',
        3: 'var(--space-3, 0.75rem)',
        4: 'var(--space-4, 1rem)',
        5: 'var(--space-5, 1.25rem)',
        6: 'var(--space-6, 1.5rem)',
        7: 'var(--space-7, 1.75rem)',
        8: 'var(--space-8, 2rem)',
        9: 'var(--space-9, 2.25rem)',
        10: 'var(--space-10, 2.5rem)',
        11: 'var(--space-11, 2.75rem)',
        12: 'var(--space-12, 3rem)',
        16: 'var(--space-16, 4rem)',
        18: 'var(--space-18, 4.5rem)',
        20: 'var(--space-20, 5rem)',
        24: 'var(--space-24, 6rem)',
        28: 'var(--space-28, 7rem)',
        32: 'var(--space-32, 8rem)',
        36: 'var(--space-36, 9rem)',
        40: 'var(--space-40, 10rem)',
        44: 'var(--space-44, 11rem)',
        48: 'var(--space-48, 12rem)',
        52: 'var(--space-52, 13rem)',
      },
      screens: {
        xs: '480px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
        '3xl': '1920px',
      },
    },
  },
  plugins: [],
  darkMode: 'class',
};

export default config;
